"""
traf_security.py — Encryption and licensing for .traf files

Produces .etraf (encrypted traffic analysis) files that:
  - Cannot be opened by generic SQLite tools
  - Require a valid license key to decrypt
  - Can be machine-locked (tied to one computer)
  - Support expiry dates
  - Are tamper-proof (authenticated encryption)

Architecture:
  .etraf file layout:
    [8 bytes]   Magic: "ETRAF\x01\x00\x00"
    [4 bytes]   Header length (uint32 LE)
    [N bytes]   Header (JSON, unencrypted — contains metadata for license validation)
    [12 bytes]  AES-GCM nonce
    [16 bytes]  AES-GCM auth tag
    [M bytes]   Encrypted SQLite data (AES-256-GCM)

  Encryption key derivation:
    data_key = random 32 bytes (generated per file)
    encrypted_data_key = AES-256-GCM(data_key, key=license_derived_key)
    The encrypted data_key is stored in the header.
    
    license_derived_key = PBKDF2(license_key, salt=file_salt, iterations=100000)

Usage:
  # Encrypt (your side — after processing)
  encrypt_traf("input.traf", "output.etraf", license_key="CUST-XXXX-YYYY-ZZZZ")
  
  # Decrypt (in your viewer app)
  db_path = decrypt_traf("input.etraf", license_key="CUST-XXXX-YYYY-ZZZZ")
  reader = TrafficReader(db_path)

  # Or use the secure reader directly (decrypts to temp, auto-cleans)
  with SecureTrafficReader("input.etraf", license_key="...") as reader:
      tracks = reader.get_tracks()

License key format:
  XXXX-XXXX-XXXX-XXXX  (16 hex chars in 4 groups)
  Generated by generate_license_key()
"""

import os
import sys
import json
import struct
import hashlib
import hmac
import secrets
import tempfile
import shutil
import logging
from datetime import datetime, timedelta
from pathlib import Path

# Use cryptography library (pip install cryptography)
# Falls back to a simpler XOR-based scheme if not available
try:
    from cryptography.hazmat.primitives.ciphers.aead import AESGCM
    from cryptography.hazmat.primitives.kdf.pbkdf2 import PBKDF2HMAC
    from cryptography.hazmat.primitives import hashes
    HAS_CRYPTO = True
except ImportError:
    HAS_CRYPTO = False
    logging.warning("cryptography package not installed. Using fallback encryption. "
                    "For production use: pip install cryptography")


MAGIC = b"ETRAF\x01\x00\x00"
PBKDF2_ITERATIONS = 100_000
SALT_SIZE = 16
NONCE_SIZE = 12
TAG_SIZE = 16
KEY_SIZE = 32  # AES-256


# ──────────────────────────────────────────────────────────────
# LICENSE KEY GENERATION
# ──────────────────────────────────────────────────────────────

def generate_license_key(prefix="TRAF"):
    """
    Generate a random license key.
    Format: PREFIX-XXXX-XXXX-XXXX where X is uppercase hex.
    
    Args:
        prefix: 3-4 char prefix for key identification
    Returns:
        License key string
    """
    parts = [prefix]
    for _ in range(3):
        parts.append(secrets.token_hex(2).upper())
    return "-".join(parts)


def generate_customer_license(customer_name, expiry_days=365, 
                               machine_id=None, max_files=None):
    """
    Generate a full license bundle for a customer.
    
    Args:
        customer_name: Customer/company name
        expiry_days: License validity in days (None = perpetual)
        machine_id: Lock to specific machine (None = any machine)
        max_files: Max number of files this key can decrypt (None = unlimited)
    
    Returns:
        dict with license_key, customer_name, expiry, etc.
    """
    key = generate_license_key()
    
    license_info = {
        'license_key': key,
        'customer_name': customer_name,
        'issued_date': datetime.now().isoformat(),
        'expiry_date': (datetime.now() + timedelta(days=expiry_days)).isoformat() 
                       if expiry_days else None,
        'machine_id': machine_id,
        'max_files': max_files,
        'key_hash': hashlib.sha256(key.encode()).hexdigest()[:16],
    }
    
    return license_info


def get_machine_id():
    """
    Get a unique machine identifier for machine-locked licenses.
    Uses a combination of hardware identifiers.
    """
    import platform
    import uuid
    
    # Get MAC address + hostname + platform as machine fingerprint
    raw = f"{uuid.getnode()}-{platform.node()}-{platform.system()}-{platform.machine()}"
    return hashlib.sha256(raw.encode()).hexdigest()[:24]


# ──────────────────────────────────────────────────────────────
# KEY DERIVATION
# ──────────────────────────────────────────────────────────────

def _derive_key(license_key: str, salt: bytes) -> bytes:
    """Derive AES-256 key from license key + salt."""
    if HAS_CRYPTO:
        kdf = PBKDF2HMAC(
            algorithm=hashes.SHA256(),
            length=KEY_SIZE,
            salt=salt,
            iterations=PBKDF2_ITERATIONS,
        )
        return kdf.derive(license_key.encode('utf-8'))
    else:
        # Fallback: simple PBKDF2 via hashlib
        return hashlib.pbkdf2_hmac(
            'sha256', 
            license_key.encode('utf-8'), 
            salt, 
            PBKDF2_ITERATIONS,
            dklen=KEY_SIZE
        )


def _encrypt_bytes(data: bytes, key: bytes) -> tuple:
    """Encrypt data with AES-256-GCM. Returns (nonce, ciphertext_with_tag)."""
    nonce = secrets.token_bytes(NONCE_SIZE)
    
    if HAS_CRYPTO:
        aesgcm = AESGCM(key)
        ciphertext = aesgcm.encrypt(nonce, data, None)
        return nonce, ciphertext
    else:
        # Fallback: AES-CTR-like with HMAC for authentication
        # This is NOT as secure as AES-GCM but works without dependencies
        return _fallback_encrypt(data, key, nonce)


def _decrypt_bytes(nonce: bytes, ciphertext: bytes, key: bytes) -> bytes:
    """Decrypt AES-256-GCM ciphertext. Raises on tampering."""
    if HAS_CRYPTO:
        aesgcm = AESGCM(key)
        return aesgcm.decrypt(nonce, ciphertext, None)
    else:
        return _fallback_decrypt(nonce, ciphertext, key)


def _fallback_encrypt(data: bytes, key: bytes, nonce: bytes) -> tuple:
    """Fallback encryption using XOR stream + HMAC auth (when cryptography pkg unavailable)."""
    # Generate keystream via SHA-256 CTR mode
    ciphertext = bytearray(len(data))
    block_size = 32
    for i in range(0, len(data), block_size):
        counter = struct.pack('<Q', i // block_size)
        block_key = hashlib.sha256(key + nonce + counter).digest()
        end = min(i + block_size, len(data))
        for j in range(i, end):
            ciphertext[j] = data[j] ^ block_key[j - i]
    
    # Auth tag
    tag = hmac.new(key, nonce + bytes(ciphertext), hashlib.sha256).digest()[:TAG_SIZE]
    return nonce, bytes(ciphertext) + tag


def _fallback_decrypt(nonce: bytes, ciphertext_with_tag: bytes, key: bytes) -> bytes:
    """Fallback decryption."""
    ciphertext = ciphertext_with_tag[:-TAG_SIZE]
    tag = ciphertext_with_tag[-TAG_SIZE:]
    
    # Verify tag
    expected_tag = hmac.new(key, nonce + ciphertext, hashlib.sha256).digest()[:TAG_SIZE]
    if not hmac.compare_digest(tag, expected_tag):
        raise ValueError("Authentication failed — file is tampered or wrong license key")
    
    # Decrypt
    plaintext = bytearray(len(ciphertext))
    block_size = 32
    for i in range(0, len(ciphertext), block_size):
        counter = struct.pack('<Q', i // block_size)
        block_key = hashlib.sha256(key + nonce + counter).digest()
        end = min(i + block_size, len(ciphertext))
        for j in range(i, end):
            plaintext[j] = ciphertext[j] ^ block_key[j - i]
    
    return bytes(plaintext)


# ──────────────────────────────────────────────────────────────
# ENCRYPT / DECRYPT .traf → .etraf
# ──────────────────────────────────────────────────────────────

def encrypt_traf(input_path, output_path, license_key,
                 customer_name=None, expiry_date=None,
                 machine_id=None):
    """
    Encrypt a .traf file into an .etraf file.
    
    Args:
        input_path: path to .traf SQLite file
        output_path: path for .etraf encrypted output
        license_key: customer's license key
        customer_name: optional customer name (stored in header, unencrypted)
        expiry_date: optional expiry as ISO date string or datetime
        machine_id: optional machine lock (from get_machine_id())
    
    Returns:
        output_path
    """
    if not os.path.exists(input_path):
        raise FileNotFoundError(f"Input file not found: {input_path}")
    
    # Read the SQLite data
    with open(input_path, 'rb') as f:
        plaintext = f.read()
    
    # Generate per-file salt and data key
    file_salt = secrets.token_bytes(SALT_SIZE)
    data_key = secrets.token_bytes(KEY_SIZE)
    
    # Derive license key → encryption key for wrapping the data key
    license_derived_key = _derive_key(license_key, file_salt)
    
    # Encrypt the data key with the license-derived key
    dk_nonce = secrets.token_bytes(NONCE_SIZE)
    dk_nonce, encrypted_data_key = _encrypt_bytes(data_key, license_derived_key)
    
    # Encrypt the actual data with the data key
    data_nonce, encrypted_data = _encrypt_bytes(plaintext, data_key)
    
    # Build header (unencrypted metadata)
    if isinstance(expiry_date, datetime):
        expiry_date = expiry_date.isoformat()
    
    header = {
        'version': '1.0',
        'created': datetime.now().isoformat(),
        'customer': customer_name,
        'expiry': expiry_date,
        'machine_lock': machine_id is not None,
        'machine_id_hash': hashlib.sha256(machine_id.encode()).hexdigest()[:16] 
                           if machine_id else None,
        'file_salt': file_salt.hex(),
        'dk_nonce': dk_nonce.hex(),
        'encrypted_data_key': encrypted_data_key.hex(),
        'original_size': len(plaintext),
        'key_check': hashlib.sha256(license_key.encode()).hexdigest()[:8],
    }
    header_bytes = json.dumps(header, indent=None).encode('utf-8')
    
    # Write .etraf file
    with open(output_path, 'wb') as f:
        f.write(MAGIC)
        f.write(struct.pack('<I', len(header_bytes)))
        f.write(header_bytes)
        f.write(data_nonce)
        f.write(encrypted_data)
    
    file_size = os.path.getsize(output_path) / (1024 * 1024)
    logging.info(f"Encrypted: {input_path} → {output_path} ({file_size:.1f} MB)")
    
    return output_path


def decrypt_traf(input_path, license_key, output_path=None,
                 verify_machine=False):
    """
    Decrypt an .etraf file back to .traf (SQLite).
    
    Args:
        input_path: path to .etraf file
        license_key: customer's license key
        output_path: where to write decrypted .traf (default: temp file)
        verify_machine: check machine_id matches current machine
    
    Returns:
        path to decrypted .traf file
    
    Raises:
        ValueError: wrong key, expired, or tampered
        PermissionError: machine-locked to different machine
    """
    with open(input_path, 'rb') as f:
        # Read magic
        magic = f.read(8)
        if magic != MAGIC:
            raise ValueError("Not a valid .etraf file")
        
        # Read header
        header_len = struct.unpack('<I', f.read(4))[0]
        header_bytes = f.read(header_len)
        header = json.loads(header_bytes.decode('utf-8'))
        
        # Read encrypted data
        data_nonce = f.read(NONCE_SIZE)
        encrypted_data = f.read()
    
    # --- Validate license ---
    
    # Quick key check (fast rejection of wrong keys)
    key_check = hashlib.sha256(license_key.encode()).hexdigest()[:8]
    if key_check != header.get('key_check'):
        raise ValueError("Invalid license key")
    
    # Check expiry
    expiry = header.get('expiry')
    if expiry:
        expiry_dt = datetime.fromisoformat(expiry)
        if datetime.now() > expiry_dt:
            raise ValueError(f"License expired on {expiry}")
    
    # Check machine lock
    if header.get('machine_lock') and verify_machine:
        current_machine = get_machine_id()
        current_hash = hashlib.sha256(current_machine.encode()).hexdigest()[:16]
        if current_hash != header.get('machine_id_hash'):
            raise PermissionError(
                "This file is locked to a different machine. "
                "Contact support for a machine transfer.")
    
    # --- Decrypt ---
    
    # Derive key from license
    file_salt = bytes.fromhex(header['file_salt'])
    license_derived_key = _derive_key(license_key, file_salt)
    
    # Decrypt the data key
    dk_nonce = bytes.fromhex(header['dk_nonce'])
    encrypted_data_key = bytes.fromhex(header['encrypted_data_key'])
    
    try:
        data_key = _decrypt_bytes(dk_nonce, encrypted_data_key, license_derived_key)
    except Exception:
        raise ValueError("Invalid license key — cannot decrypt")
    
    # Decrypt the actual data
    try:
        plaintext = _decrypt_bytes(data_nonce, encrypted_data, data_key)
    except Exception:
        raise ValueError("File is corrupted or has been tampered with")
    
    # Verify size
    expected_size = header.get('original_size')
    if expected_size and len(plaintext) != expected_size:
        raise ValueError("Decrypted data size mismatch — file may be corrupted")
    
    # Write decrypted file
    if output_path is None:
        fd, output_path = tempfile.mkstemp(suffix='.traf')
        os.close(fd)
    
    with open(output_path, 'wb') as f:
        f.write(plaintext)
    
    return output_path


def read_etraf_header(input_path):
    """
    Read the unencrypted header of an .etraf file.
    Useful for displaying file info without decryption.
    
    Returns:
        dict with header metadata (customer, expiry, etc.)
    """
    with open(input_path, 'rb') as f:
        magic = f.read(8)
        if magic != MAGIC:
            raise ValueError("Not a valid .etraf file")
        header_len = struct.unpack('<I', f.read(4))[0]
        header_bytes = f.read(header_len)
    return json.loads(header_bytes.decode('utf-8'))


# ──────────────────────────────────────────────────────────────
# SECURE READER (context manager)
# ──────────────────────────────────────────────────────────────

class SecureTrafficReader:
    """
    Open an .etraf file with automatic decryption and cleanup.
    Works as a drop-in replacement for TrafficReader.
    
    Usage:
        with SecureTrafficReader("data.etraf", license_key="TRAF-ABCD-1234-EF56") as reader:
            summary = reader.summary()
            tracks = reader.get_tracks(class_name="PV")
    """
    
    def __init__(self, etraf_path, license_key, verify_machine=False):
        self.etraf_path = etraf_path
        self.license_key = license_key
        self.verify_machine = verify_machine
        self._temp_path = None
        self._reader = None
    
    def __enter__(self):
        from traffic_export import TrafficReader
        self._temp_path = decrypt_traf(
            self.etraf_path, self.license_key,
            verify_machine=self.verify_machine)
        self._reader = TrafficReader(self._temp_path)
        return self._reader
    
    def __exit__(self, *args):
        if self._reader:
            self._reader.close()
        if self._temp_path and os.path.exists(self._temp_path):
            # Securely delete temp file
            try:
                # Overwrite with random data before deleting
                size = os.path.getsize(self._temp_path)
                with open(self._temp_path, 'wb') as f:
                    f.write(secrets.token_bytes(min(size, 4096)))
                os.remove(self._temp_path)
            except Exception:
                try:
                    os.remove(self._temp_path)
                except Exception:
                    pass


# ──────────────────────────────────────────────────────────────
# CLI
# ──────────────────────────────────────────────────────────────

def main():
    import argparse
    
    parser = argparse.ArgumentParser(
        description="Traffic Analysis File Security Tool",
        formatter_class=argparse.RawDescriptionHelpFormatter,
        epilog="""
Examples:
  # Generate a license key
  python traf_security.py generate-key --customer "Acme Corp" --days 365
  
  # Encrypt a .traf file
  python traf_security.py encrypt data.traf data.etraf --key TRAF-A1B2-C3D4-E5F6
  
  # Decrypt (for testing)
  python traf_security.py decrypt data.etraf data_decrypted.traf --key TRAF-A1B2-C3D4-E5F6
  
  # Show file info
  python traf_security.py info data.etraf
  
  # Get machine ID (for machine-locked licenses)
  python traf_security.py machine-id
        """)
    
    sub = parser.add_subparsers(dest='command')
    
    # generate-key
    gen = sub.add_parser('generate-key', help='Generate a license key')
    gen.add_argument('--customer', required=True, help='Customer name')
    gen.add_argument('--days', type=int, default=365, help='Validity in days')
    gen.add_argument('--machine-lock', action='store_true', help='Lock to current machine')
    
    # encrypt
    enc = sub.add_parser('encrypt', help='Encrypt .traf → .etraf')
    enc.add_argument('input', help='Input .traf file')
    enc.add_argument('output', help='Output .etraf file')
    enc.add_argument('--key', required=True, help='License key')
    enc.add_argument('--customer', help='Customer name')
    enc.add_argument('--expiry', help='Expiry date (YYYY-MM-DD)')
    enc.add_argument('--machine-id', help='Lock to machine ID')
    
    # decrypt
    dec = sub.add_parser('decrypt', help='Decrypt .etraf → .traf')
    dec.add_argument('input', help='Input .etraf file')
    dec.add_argument('output', help='Output .traf file')
    dec.add_argument('--key', required=True, help='License key')
    
    # info
    inf = sub.add_parser('info', help='Show .etraf file info')
    inf.add_argument('input', help='.etraf file')
    
    # machine-id
    sub.add_parser('machine-id', help='Show current machine ID')
    
    args = parser.parse_args()
    
    if args.command == 'generate-key':
        machine_id = get_machine_id() if args.machine_lock else None
        license_info = generate_customer_license(
            args.customer, args.days, machine_id=machine_id)
        print(f"License Key:  {license_info['license_key']}")
        print(f"Customer:     {license_info['customer_name']}")
        print(f"Issued:       {license_info['issued_date']}")
        print(f"Expires:      {license_info['expiry_date'] or 'Never'}")
        if machine_id:
            print(f"Machine ID:   {machine_id}")
        print(f"\nStore this key securely — it cannot be recovered!")
    
    elif args.command == 'encrypt':
        expiry = None
        if args.expiry:
            expiry = datetime.strptime(args.expiry, '%Y-%m-%d').isoformat()
        encrypt_traf(args.input, args.output, args.key,
                     customer_name=args.customer, expiry_date=expiry,
                     machine_id=args.machine_id)
        print(f"Encrypted: {args.input} → {args.output}")
    
    elif args.command == 'decrypt':
        decrypt_traf(args.input, args.key, args.output)
        print(f"Decrypted: {args.input} → {args.output}")
    
    elif args.command == 'info':
        header = read_etraf_header(args.input)
        print(f"=== .etraf File Info ===")
        print(f"Format version: {header.get('version')}")
        print(f"Created:        {header.get('created')}")
        print(f"Customer:       {header.get('customer', 'N/A')}")
        print(f"Expiry:         {header.get('expiry', 'None')}")
        print(f"Machine locked: {header.get('machine_lock', False)}")
        print(f"Original size:  {header.get('original_size', 0) / 1024:.1f} KB")
    
    elif args.command == 'machine-id':
        print(f"Machine ID: {get_machine_id()}")
    
    else:
        parser.print_help()


if __name__ == "__main__":
    main()
